version: "3"

services:
  frontend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.frontend
    ports:
      - "8081:80"

  backend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.backend
    ports:
      - "5000:3000"

  prometheus:
    image: prom/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
