name: Deploy App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build images
        run: |
          echo "Project strucutre:"
          ls -R
          
          docker build -t frontend -f Docker/Dockerfile.frontend .
          docker build -t backend -f Docker/Dockerfile.backend .

      - name: SSH Deploy
        run: |
          ssh ubuntu@EC2_IP "
            docker-compose down
            docker-compose up -d --build
          "
