
      


        
name: Deploy App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images (CI check)
        run: |
          echo "Project structure:"
          ls -R
          
          docker build -t frontend -f Docker/Dockerfile.frontend .
          docker build -t backend -f Docker/Dockerfile.backend .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

            echo "🚀 Starting Deployment..."

            # Clone if not exists
            if [ ! -d "hackathon-project" ]; then
              git clone https://github.com/arunessential/hackathon-project.git
            fi

            cd hackathon-project

            # Pull latest code
            git pull origin main

            # Ensure Docker is running
            sudo systemctl start docker

            # Stop existing containers
            docker compose -f Docker/docker-compose.yml down || true

            # Build & start containers
            docker compose -f Docker/docker-compose.yml up -d --build

            echo "✅ Deployment Complete"

          EOF
